baseURL = "https://jum.github.io/"
languageCode = "en-us"
title = "jum's random musings"
theme = "ananke"

[params]
  twitter = "https://twitter.com/jumager"
  featured_image = "/images/P1060724.JPG"
